/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.example.MultipleAuthTester.models.operations;

import com.example.MultipleAuthTester.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class GetCarsByCNICRequest {
    /**
     * CNIC of a person
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=cnic")
    public String cnic;

    public GetCarsByCNICRequest withCnic(String cnic) {
        this.cnic = cnic;
        return this;
    }
    
    public GetCarsByCNICRequest(@JsonProperty("cnic") String cnic) {
        this.cnic = cnic;
  }
}
