/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.example.MultipleAuthTester.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetCarsByNameResponse {
    /**
     * car response
     */
    
    public com.example.MultipleAuthTester.models.shared.Car[] cars;

    public GetCarsByNameResponse withCars(com.example.MultipleAuthTester.models.shared.Car[] cars) {
        this.cars = cars;
        return this;
    }
    
    
    public String contentType;

    public GetCarsByNameResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * error payload
     */
    
    public com.example.MultipleAuthTester.models.shared.ErrorModel errorModel;

    public GetCarsByNameResponse withErrorModel(com.example.MultipleAuthTester.models.shared.ErrorModel errorModel) {
        this.errorModel = errorModel;
        return this;
    }
    
    
    public Integer statusCode;

    public GetCarsByNameResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetCarsByNameResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetCarsByNameResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
