/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.example.MultipleAuthTester.models.operations;

import com.example.MultipleAuthTester.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class GetCarsByNameSecurity {
    @SpeakeasyMetadata("security:scheme=true,type=apiKey,subtype=header,name=X-API-KEY")
    public String apiKeyHeader;

    public GetCarsByNameSecurity withApiKeyHeader(String apiKeyHeader) {
        this.apiKeyHeader = apiKeyHeader;
        return this;
    }
    
    @SpeakeasyMetadata("security:scheme=true,type=http,subtype=basic")
    public com.example.MultipleAuthTester.models.shared.SchemeHTTPBasic httpBasic;

    public GetCarsByNameSecurity withHttpBasic(com.example.MultipleAuthTester.models.shared.SchemeHTTPBasic httpBasic) {
        this.httpBasic = httpBasic;
        return this;
    }
    
    public GetCarsByNameSecurity(@JsonProperty("apiKeyHeader") String apiKeyHeader, @JsonProperty("httpBasic") com.example.MultipleAuthTester.models.shared.SchemeHTTPBasic httpBasic) {
        this.apiKeyHeader = apiKeyHeader;
        this.httpBasic = httpBasic;
  }
}
