/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.example.MultipleAuthTester.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class ErrorModel {
    @JsonProperty("code")
    public Long code;

    public ErrorModel withCode(Long code) {
        this.code = code;
        return this;
    }
    
    @JsonProperty("message")
    public String message;

    public ErrorModel withMessage(String message) {
        this.message = message;
        return this;
    }
    
    public ErrorModel(@JsonProperty("code") Long code, @JsonProperty("message") String message) {
        this.code = code;
        this.message = message;
  }
}
