/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.example.MultipleAuthTester.models.shared;

import com.example.MultipleAuthTester.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class SchemeHTTPBasic {
    @SpeakeasyMetadata("security:name=password")
    public String password;

    public SchemeHTTPBasic withPassword(String password) {
        this.password = password;
        return this;
    }
    
    @SpeakeasyMetadata("security:name=username")
    public String username;

    public SchemeHTTPBasic withUsername(String username) {
        this.username = username;
        return this;
    }
    
    public SchemeHTTPBasic(@JsonProperty("Username") String username, @JsonProperty("Password") String password) {
        this.username = username;
        this.password = password;
  }
}
