/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.example.MultipleAuthTester.models.shared;

import com.example.MultipleAuthTester.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class Security {
    @SpeakeasyMetadata("security:scheme=true,type=apiKey,subtype=query,name=api_key")
    public String apiKey;

    public Security withApiKey(String apiKey) {
        this.apiKey = apiKey;
        return this;
    }
    
    @SpeakeasyMetadata("security:scheme=true,type=http,subtype=basic")
    public SchemeHTTPBasic httpBasic;

    public Security withHttpBasic(SchemeHTTPBasic httpBasic) {
        this.httpBasic = httpBasic;
        return this;
    }
    
    public Security(@JsonProperty("apiKey") String apiKey, @JsonProperty("httpBasic") SchemeHTTPBasic httpBasic) {
        this.apiKey = apiKey;
        this.httpBasic = httpBasic;
  }
}
